---
- name: My Test Playbook
  hosts: all
  become: yes
  tasks:
  - name: creating multiple users
    user: name='{{item}}' state=present
    with_items:
     - user1
     - user2
     - user3
     - user4  

