---
- name: My Test Playbook
  hosts: all
  become: yes
  tasks:
  - name: installing a package httpd
    yum:
      name: httpd
      state: installed
    notify: start service
  handlers:    
  - name: start service
    service:
      name: httpd
      state: started
