---
- name: Tomcat Playbook
  hosts: all
  become: true
  tasks:
  - name: installing java in redhat
    yum: 
      name: java
      state: present
    when: ansible_os_family == "RedHat"  

  - name: installing java in debian
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"
  
  - name: Download tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz
      dest: /opt

  - name: Extracting tomcat
    unarchive:
      src: /opt/apache-tomcat-8.5.78.tar.gz
      dest: /opt
      remote_src: yes
  
  - name: Giving excute permissions
    file:
      path: /opt/apache-tomcat-8.5.78/bin/startup.sh
      mode: 0777
  
  - name: start tomcat service
    shell: nohup ./startup.sh 
    args:
      chdir: /opt/apache-tomcat-8.5.78/bin    
